- name: Remove App code
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Download and extract {{ COMPONENT }} component archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy {{ COMPONENT }} code to app location
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: "{{ APP_LOCATION }}/{{ SUFFIX }}"/
    remote_src: yes


