- name: Create application user
  ansible.builtin.user:
    name: roboshop

- name: Remove App location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Create App location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory

- name: Download and extract {{ COMPONENT }} component archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy {{ COMPONENT }} code to app location
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/{{SUFFIX}}
    dest: "{{APP_LOCATION}}/"
    remote_src: yes


