- name: Setup YUM repo fpr nodejs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing nodeJS
  ansible.builtin.yum:
     name: nodejs
     state: installed

- name: Import common role for downlaod
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install nodeJS dependencies
  community.general.npm:
    path: "{{ APP_LOCATION }}"

- name: Systemd setup fpr {{ COMPONENT }} service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

