- name: Setup {{ COMPONENT }} systemd service
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{ COMPONENT}}"
    enabled: yes
    state: started
    daemon_reload: yes